Logging started at 2016-07-14 17:48:57
File name: C:\Users\Administrator\Dropbox\lunarisle source\.\data\logs\err\1468511337332 - Administrator - [Thu Jul 14][5.48PM].txt
System.getProperty("os.name"): "Windows Server 2012 R2"

[2016-07-14 17:51:58] java.lang.NullPointerException
[2016-07-14 17:51:58] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:51:58] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:51:58] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:51:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:51:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:51:58] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:51:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:51:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 17:52:01] java.lang.NullPointerException
[2016-07-14 17:52:01] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:52:01] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:52:01] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:52:01] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:52:01] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:52:01] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:52:01] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:52:01] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 17:52:02] java.lang.NullPointerException
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 17:52:02] java.lang.NullPointerException
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 17:52:02] java.lang.NullPointerException
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 17:52:02] java.lang.NullPointerException
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 17:52:02] java.lang.NullPointerException
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 17:52:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 17:52:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:11] java.lang.NullPointerException
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:11] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:11] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:11] java.lang.NullPointerException
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:11] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:11] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:11] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:12] java.lang.NullPointerException
[2016-07-14 19:15:12] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:12] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:12] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:12] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:12] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:12] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:12] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:12] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:13] java.lang.NullPointerException
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:13] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:13] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:13] java.lang.NullPointerException
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:13] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:13] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:13] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:45] java.lang.NullPointerException
[2016-07-14 19:15:45] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:45] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:45] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:45] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:45] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:45] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:45] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:45] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:46] java.lang.NullPointerException
[2016-07-14 19:15:46] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:46] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:46] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:46] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:46] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:46] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:46] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:46] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:47] java.lang.NullPointerException
[2016-07-14 19:15:47] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:47] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:47] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:213)
[2016-07-14 19:15:47] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:47] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:47] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:47] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:47] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:49] java.lang.NullPointerException
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:49] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:49] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:49] java.lang.NullPointerException
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:49] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:49] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:49] java.lang.NullPointerException
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:49] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:49] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:49] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:50] java.lang.NullPointerException
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:50] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:50] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:50] java.lang.NullPointerException
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:50] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:50] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:50] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:54] java.lang.NullPointerException
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:54] java.lang.NullPointerException
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:54] java.lang.NullPointerException
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:54] java.lang.NullPointerException
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:15:54] java.lang.NullPointerException
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:15:54] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:15:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:16:03] java.lang.NullPointerException
[2016-07-14 19:16:03] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:16:03] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:16:03] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:16:03] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:16:03] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:16:03] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:16:03] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:16:03] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:16:07] java.lang.NullPointerException
[2016-07-14 19:16:07] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:16:07] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:16:07] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:97)
[2016-07-14 19:16:07] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:16:07] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:16:07] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:16:07] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:16:07] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:16:12] java.lang.NullPointerException
[2016-07-14 19:16:12] 	at com.vencillio.rs2.entity.InterfaceManager.getParents(InterfaceManager.java:17)
[2016-07-14 19:16:12] 	at com.vencillio.rs2.entity.InterfaceManager.verify(InterfaceManager.java:89)
[2016-07-14 19:16:12] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:213)
[2016-07-14 19:16:12] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 19:16:12] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 19:16:12] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 19:16:12] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 19:16:12] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 19:41:28] java.lang.NullPointerException
[2016-07-14 19:41:28] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:41:28] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:41:28] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:47:21] java.lang.NullPointerException
[2016-07-14 19:47:21] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:47:21] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:47:21] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:47:24] java.lang.NullPointerException
[2016-07-14 19:47:24] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:47:24] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:47:24] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:47:46] java.lang.NullPointerException
[2016-07-14 19:47:46] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:47:46] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:47:46] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:07] java.lang.NullPointerException
[2016-07-14 19:48:07] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:07] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:07] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:08] java.lang.NullPointerException
[2016-07-14 19:48:08] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:08] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:08] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:09] java.lang.NullPointerException
[2016-07-14 19:48:09] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:09] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:09] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:10] java.lang.NullPointerException
[2016-07-14 19:48:10] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:10] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:10] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:11] java.lang.NullPointerException
[2016-07-14 19:48:11] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:11] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:11] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:13] java.lang.NullPointerException
[2016-07-14 19:48:13] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:13] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:13] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:16] java.lang.NullPointerException
[2016-07-14 19:48:16] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:16] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:16] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:32] java.lang.NullPointerException
[2016-07-14 19:48:32] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:32] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:32] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 19:48:47] java.lang.NullPointerException
[2016-07-14 19:48:47] 	at com.vencillio.rs2.entity.player.Player.login(Player.java:1208)
[2016-07-14 19:48:47] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:42)
[2016-07-14 19:48:47] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2016-07-14 20:03:15] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 20:03:15] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-14 20:03:15] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-14 20:03:15] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-14 20:03:15] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-14 20:03:15] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-14 20:03:15] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-14 20:03:15] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-14 20:03:15] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-14 20:03:15] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-14 20:03:15] 	at java.lang.Thread.run(Unknown Source)
[2016-07-14 20:03:15] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 20:03:15] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-14 20:03:15] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-14 20:03:15] 	... 9 more
[2016-07-14 20:03:15] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 20:03:15] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-14 20:03:15] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-14 20:03:15] 	... 10 more
[2016-07-14 20:03:15] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 20:03:15] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-14 20:03:15] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-14 20:03:15] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-14 20:03:15] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-14 20:03:15] 	... 11 more
[2016-07-14 20:04:15] com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketTimeoutException: Read timed out
[2016-07-14 20:04:15] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-14 20:04:15] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-14 20:04:15] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-14 20:04:15] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-14 20:04:15] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-14 20:04:15] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-14 20:04:15] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-14 20:04:15] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-14 20:04:15] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-14 20:04:15] 	at java.lang.Thread.run(Unknown Source)
[2016-07-14 20:04:15] Caused by: java.net.SocketTimeoutException: Read timed out
[2016-07-14 20:04:15] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2016-07-14 20:04:15] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2016-07-14 20:04:15] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-14 20:04:15] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-14 20:04:15] 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
[2016-07-14 20:04:15] 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
[2016-07-14 20:04:15] 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
[2016-07-14 20:04:15] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
[2016-07-14 20:04:15] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[2016-07-14 20:04:15] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
[2016-07-14 20:04:15] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
[2016-07-14 20:04:15] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
[2016-07-14 20:04:15] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
[2016-07-14 20:04:15] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
[2016-07-14 20:04:15] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
[2016-07-14 20:04:15] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
[2016-07-14 20:04:15] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
[2016-07-14 20:04:15] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
[2016-07-14 20:04:15] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-07-14 20:04:15] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-07-14 20:04:15] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
[2016-07-14 20:04:15] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
[2016-07-14 20:04:15] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
[2016-07-14 20:04:15] 	... 9 more
[2016-07-14 20:21:13] java.lang.NumberFormatException: For input string: "4.5000000"
[2016-07-14 20:21:13] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2016-07-14 20:21:13] 	at java.lang.Long.parseLong(Unknown Source)
[2016-07-14 20:21:13] 	at java.lang.Long.parseLong(Unknown Source)
[2016-07-14 20:21:13] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:208)
[2016-07-14 20:21:13] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 20:21:13] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 20:21:13] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 20:21:13] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 20:21:13] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 20:21:13] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 21:29:02] java.lang.NullPointerException
[2016-07-14 21:29:02] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-14 21:29:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-14 21:29:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 21:29:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 21:29:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 21:29:03] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 21:29:03] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 21:29:12] java.lang.NullPointerException
[2016-07-14 21:29:12] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-14 21:29:12] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-14 21:29:12] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 21:29:12] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 21:29:12] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 21:29:12] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 21:29:12] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:06:45] java.lang.ArrayIndexOutOfBoundsException: 249
[2016-07-14 22:06:45] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:06:45] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:06:45] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:06:45] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:06:45] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:06:45] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:06:45] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:06:54] java.lang.ArrayIndexOutOfBoundsException: 199
[2016-07-14 22:06:54] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:06:54] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:06:54] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:06:54] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:06:54] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:06:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:06:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:07:13] java.lang.ArrayIndexOutOfBoundsException: 249
[2016-07-14 22:07:13] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:07:13] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:07:13] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:07:13] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:07:13] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:07:13] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:07:13] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:09:31] java.lang.ArrayIndexOutOfBoundsException: 999
[2016-07-14 22:09:31] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:09:31] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:09:31] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:09:31] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:09:31] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:09:31] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:09:31] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:13:11] java.lang.ArrayIndexOutOfBoundsException: 999
[2016-07-14 22:13:11] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:13:11] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:13:11] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:13:11] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:13:11] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:13:11] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:13:11] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:13:15] java.lang.ArrayIndexOutOfBoundsException: 999
[2016-07-14 22:13:15] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:13:15] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:13:15] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:13:15] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:13:15] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:13:15] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:13:15] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:13:19] java.lang.ArrayIndexOutOfBoundsException: 999
[2016-07-14 22:13:19] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:13:19] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:13:19] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:13:19] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:13:19] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:13:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:13:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:13:25] java.lang.ArrayIndexOutOfBoundsException: 999
[2016-07-14 22:13:25] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:13:25] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:13:25] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:13:25] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:13:25] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:13:25] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:13:25] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:23:45] java.lang.ArrayIndexOutOfBoundsException: 25
[2016-07-14 22:23:45] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:333)
[2016-07-14 22:23:45] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:23:45] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:23:45] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:23:45] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:23:45] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:23:45] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:27:15] com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketTimeoutException: Read timed out
[2016-07-14 22:27:15] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-14 22:27:15] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-14 22:27:15] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-14 22:27:15] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-14 22:27:15] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-14 22:27:15] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-14 22:27:15] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-14 22:27:15] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-14 22:27:15] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-14 22:27:15] 	at java.lang.Thread.run(Unknown Source)
[2016-07-14 22:27:15] Caused by: java.net.SocketTimeoutException: Read timed out
[2016-07-14 22:27:15] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2016-07-14 22:27:15] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2016-07-14 22:27:15] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-14 22:27:15] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-14 22:27:15] 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
[2016-07-14 22:27:15] 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
[2016-07-14 22:27:15] 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
[2016-07-14 22:27:15] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
[2016-07-14 22:27:15] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[2016-07-14 22:27:15] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
[2016-07-14 22:27:15] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
[2016-07-14 22:27:15] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
[2016-07-14 22:27:15] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
[2016-07-14 22:27:15] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
[2016-07-14 22:27:15] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
[2016-07-14 22:27:15] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
[2016-07-14 22:27:15] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
[2016-07-14 22:27:15] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
[2016-07-14 22:27:15] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-07-14 22:27:15] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-07-14 22:27:15] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
[2016-07-14 22:27:15] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
[2016-07-14 22:27:15] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
[2016-07-14 22:27:15] 	... 9 more
[2016-07-14 22:27:39] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 22:27:39] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-14 22:27:39] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-14 22:27:39] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-14 22:27:39] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-14 22:27:39] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-14 22:27:39] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-14 22:27:39] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-14 22:27:39] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-14 22:27:39] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-14 22:27:39] 	at java.lang.Thread.run(Unknown Source)
[2016-07-14 22:27:39] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 22:27:39] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-14 22:27:39] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-14 22:27:39] 	... 9 more
[2016-07-14 22:27:39] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 22:27:39] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-14 22:27:39] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-14 22:27:39] 	... 10 more
[2016-07-14 22:27:39] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-14 22:27:39] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-14 22:27:39] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-14 22:27:39] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-14 22:27:39] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-14 22:27:39] 	... 11 more
[2016-07-14 22:28:21] java.lang.ArrayIndexOutOfBoundsException: 104
[2016-07-14 22:28:21] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:28:21] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:28:21] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:28:21] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:28:21] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:28:21] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:28:21] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:28:24] java.lang.ArrayIndexOutOfBoundsException: 104
[2016-07-14 22:28:24] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:28:24] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:28:24] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:28:24] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:28:24] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:28:24] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:28:24] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:28:36] java.lang.ArrayIndexOutOfBoundsException: 101
[2016-07-14 22:28:36] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:28:36] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:28:36] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:28:36] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:28:36] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:28:36] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:28:36] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:28:39] java.lang.ArrayIndexOutOfBoundsException: 104
[2016-07-14 22:28:39] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:28:39] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:28:39] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:28:39] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:28:39] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:28:39] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:28:39] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:28:48] java.lang.ArrayIndexOutOfBoundsException: 149
[2016-07-14 22:28:48] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:28:48] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:28:48] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:28:48] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:28:48] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:28:48] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:28:48] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:28:58] java.lang.ArrayIndexOutOfBoundsException: 101
[2016-07-14 22:28:58] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:28:58] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:28:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:28:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:28:58] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:28:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:28:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:29:33] java.lang.ArrayIndexOutOfBoundsException: 109
[2016-07-14 22:29:33] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:29:33] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:29:33] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:29:33] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:29:33] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:29:33] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:29:33] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:29:40] java.lang.ArrayIndexOutOfBoundsException: 101
[2016-07-14 22:29:40] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:29:40] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:29:40] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:29:40] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:29:40] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:29:40] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:29:40] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:29:44] java.lang.ArrayIndexOutOfBoundsException: 109
[2016-07-14 22:29:44] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:29:44] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:29:44] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:29:44] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:29:44] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:29:44] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:29:44] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:29:52] com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketTimeoutException: Read timed out
[2016-07-14 22:29:52] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-14 22:29:52] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-14 22:29:52] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-14 22:29:52] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-14 22:29:52] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-14 22:29:52] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-14 22:29:52] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-14 22:29:52] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-14 22:29:52] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-14 22:29:52] 	at java.lang.Thread.run(Unknown Source)
[2016-07-14 22:29:52] Caused by: java.net.SocketTimeoutException: Read timed out
[2016-07-14 22:29:52] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2016-07-14 22:29:52] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2016-07-14 22:29:52] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-14 22:29:52] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-14 22:29:52] 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
[2016-07-14 22:29:52] 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
[2016-07-14 22:29:52] 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
[2016-07-14 22:29:52] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
[2016-07-14 22:29:52] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[2016-07-14 22:29:52] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
[2016-07-14 22:29:52] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
[2016-07-14 22:29:52] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
[2016-07-14 22:29:52] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
[2016-07-14 22:29:52] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
[2016-07-14 22:29:52] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
[2016-07-14 22:29:52] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
[2016-07-14 22:29:52] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
[2016-07-14 22:29:52] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
[2016-07-14 22:29:52] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-07-14 22:29:52] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-07-14 22:29:52] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
[2016-07-14 22:29:52] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
[2016-07-14 22:29:52] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
[2016-07-14 22:29:52] 	... 9 more
[2016-07-14 22:30:00] java.lang.ArrayIndexOutOfBoundsException: 149
[2016-07-14 22:30:00] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:30:00] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:30:00] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:30:00] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:30:00] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:30:00] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:30:00] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:30:27] java.lang.ArrayIndexOutOfBoundsException: 119
[2016-07-14 22:30:27] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:30:27] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:30:27] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:30:27] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:30:27] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:30:27] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:30:27] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:31:31] java.lang.ArrayIndexOutOfBoundsException: 199
[2016-07-14 22:31:31] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:31:31] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:31:31] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:31:31] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:31:31] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:31:31] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:31:31] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:32:30] java.lang.ArrayIndexOutOfBoundsException: 221
[2016-07-14 22:32:30] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:32:30] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:32:30] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:32:30] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:32:30] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:32:30] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:32:30] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:34:49] java.lang.IllegalArgumentException: bound must be positive
[2016-07-14 22:34:49] 	at java.util.Random.nextInt(Unknown Source)
[2016-07-14 22:34:49] 	at com.vencillio.rs2.content.combat.Combat.next(Combat.java:32)
[2016-07-14 22:34:49] 	at com.vencillio.rs2.content.combat.impl.Melee.execute(Melee.java:44)
[2016-07-14 22:34:49] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:82)
[2016-07-14 22:34:49] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2016-07-14 22:34:49] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1545)
[2016-07-14 22:34:49] 	at com.vencillio.rs2.entity.World.process(World.java:322)
[2016-07-14 22:34:49] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:34:49] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:35:03] java.lang.IllegalArgumentException: bound must be positive
[2016-07-14 22:35:03] 	at java.util.Random.nextInt(Unknown Source)
[2016-07-14 22:35:03] 	at com.vencillio.rs2.content.combat.Combat.next(Combat.java:32)
[2016-07-14 22:35:03] 	at com.vencillio.rs2.content.combat.impl.Melee.execute(Melee.java:44)
[2016-07-14 22:35:03] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:82)
[2016-07-14 22:35:03] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2016-07-14 22:35:03] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1545)
[2016-07-14 22:35:03] 	at com.vencillio.rs2.entity.World.process(World.java:322)
[2016-07-14 22:35:03] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:35:03] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:38:45] java.lang.ArrayIndexOutOfBoundsException: 199
[2016-07-14 22:38:45] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:38:45] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:38:45] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:38:45] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:38:45] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:38:45] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:38:45] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:47:26] java.lang.ArrayIndexOutOfBoundsException: 199
[2016-07-14 22:47:26] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:47:26] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:47:26] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:47:26] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:47:26] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:47:26] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:47:26] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:47:31] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-14 22:47:31] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:47:31] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:47:31] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:47:31] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:47:31] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:47:31] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:47:31] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:58:19] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-14 22:58:19] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:58:19] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:58:19] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:58:19] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:58:19] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:58:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:58:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-14 22:59:29] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-14 22:59:29] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-14 22:59:29] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-14 22:59:29] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-14 22:59:29] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-14 22:59:29] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-14 22:59:29] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-14 22:59:29] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 00:43:58] java.lang.ArrayIndexOutOfBoundsException: 64
[2016-07-15 00:43:58] 	at com.vencillio.core.util.Utility.textUnpack(Utility.java:715)
[2016-07-15 00:43:58] 	at com.vencillio.rs2.entity.ReportHandler.addText(ReportHandler.java:28)
[2016-07-15 00:43:58] 	at com.vencillio.rs2.entity.player.net.in.impl.PublicChatPacket.handle(PublicChatPacket.java:61)
[2016-07-15 00:43:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-15 00:43:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-15 00:43:58] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-15 00:43:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 00:43:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 00:44:09] java.lang.ArrayIndexOutOfBoundsException: 64
[2016-07-15 00:44:09] 	at com.vencillio.core.util.Utility.textUnpack(Utility.java:715)
[2016-07-15 00:44:09] 	at com.vencillio.rs2.entity.ReportHandler.addText(ReportHandler.java:28)
[2016-07-15 00:44:09] 	at com.vencillio.rs2.entity.player.net.in.impl.PublicChatPacket.handle(PublicChatPacket.java:61)
[2016-07-15 00:44:09] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-15 00:44:09] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-15 00:44:09] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-15 00:44:09] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 00:44:09] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 00:48:34] java.lang.ArrayIndexOutOfBoundsException: 249
[2016-07-15 00:48:34] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-15 00:48:34] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-15 00:48:34] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-15 00:48:34] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-15 00:48:34] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-15 00:48:34] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 00:48:34] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 00:50:54] java.lang.ArrayIndexOutOfBoundsException
[2016-07-15 00:51:34] java.lang.ArrayIndexOutOfBoundsException
[2016-07-15 01:09:56] java.lang.NullPointerException
[2016-07-15 01:09:56] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1545)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.entity.World.process(World.java:322)
[2016-07-15 01:09:56] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 01:09:56] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 01:09:56] java.lang.NullPointerException
[2016-07-15 01:09:56] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1471)
[2016-07-15 01:09:56] 	at com.vencillio.rs2.entity.World.process(World.java:335)
[2016-07-15 01:09:56] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 01:09:56] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 01:11:34] java.lang.NullPointerException
[2016-07-15 01:11:34] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1545)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.entity.World.process(World.java:322)
[2016-07-15 01:11:34] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 01:11:34] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 01:11:34] java.lang.NullPointerException
[2016-07-15 01:11:34] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1471)
[2016-07-15 01:11:34] 	at com.vencillio.rs2.entity.World.process(World.java:335)
[2016-07-15 01:11:34] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 01:11:34] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 01:20:59] java.lang.ArrayIndexOutOfBoundsException: 154
[2016-07-15 01:20:59] 	at com.vencillio.rs2.content.bank.Bank.changeTabAmount(Bank.java:415)
[2016-07-15 01:20:59] 	at com.vencillio.rs2.content.bank.Bank.withdraw(Bank.java:348)
[2016-07-15 01:20:59] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.withdrawBankItem(ItemPackets.java:1116)
[2016-07-15 01:20:59] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:167)
[2016-07-15 01:20:59] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-15 01:20:59] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-15 01:20:59] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-15 01:20:59] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 01:20:59] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 02:08:42] java.lang.NullPointerException
[2016-07-15 02:08:42] java.lang.NullPointerException
[2016-07-15 02:08:42] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2016-07-15 02:08:42] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2016-07-15 02:08:42] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1471)
[2016-07-15 02:08:42] 	at com.vencillio.rs2.entity.World.process(World.java:335)
[2016-07-15 02:08:42] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 02:08:42] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 02:15:02] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:15:02] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 02:15:02] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 02:15:02] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 02:15:02] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 02:15:02] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 02:15:02] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 02:15:02] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 02:15:02] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 02:15:02] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 02:15:02] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 02:15:02] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:15:02] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 02:15:02] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 02:15:02] 	... 9 more
[2016-07-15 02:15:02] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:15:02] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 02:15:02] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 02:15:02] 	... 10 more
[2016-07-15 02:15:02] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:15:02] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 02:15:02] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 02:15:02] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 02:15:02] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 02:15:02] 	... 11 more
[2016-07-15 02:16:08] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:16:08] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 02:16:08] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 02:16:08] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 02:16:08] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 02:16:08] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 02:16:08] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 02:16:08] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 02:16:08] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 02:16:08] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 02:16:08] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 02:16:08] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:16:08] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 02:16:08] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 02:16:08] 	... 9 more
[2016-07-15 02:16:08] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:16:08] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 02:16:08] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 02:16:08] 	... 10 more
[2016-07-15 02:16:08] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 02:16:08] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 02:16:08] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 02:16:08] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 02:16:08] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 02:16:08] 	... 11 more
[2016-07-15 02:17:08] com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketTimeoutException: Read timed out
[2016-07-15 02:17:08] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 02:17:08] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 02:17:08] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 02:17:08] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 02:17:08] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 02:17:08] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 02:17:08] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 02:17:08] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 02:17:08] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 02:17:08] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 02:17:08] Caused by: java.net.SocketTimeoutException: Read timed out
[2016-07-15 02:17:08] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2016-07-15 02:17:08] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2016-07-15 02:17:08] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-15 02:17:08] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-15 02:17:08] 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
[2016-07-15 02:17:08] 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
[2016-07-15 02:17:08] 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
[2016-07-15 02:17:08] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
[2016-07-15 02:17:08] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[2016-07-15 02:17:08] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
[2016-07-15 02:17:08] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
[2016-07-15 02:17:08] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
[2016-07-15 02:17:08] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
[2016-07-15 02:17:08] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
[2016-07-15 02:17:08] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
[2016-07-15 02:17:08] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
[2016-07-15 02:17:08] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
[2016-07-15 02:17:08] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
[2016-07-15 02:17:08] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-07-15 02:17:08] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-07-15 02:17:08] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
[2016-07-15 02:17:08] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
[2016-07-15 02:17:08] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
[2016-07-15 02:17:08] 	... 9 more
[2016-07-15 04:18:19] java.lang.NullPointerException
[2016-07-15 04:18:19] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2016-07-15 04:18:19] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2016-07-15 04:18:19] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2016-07-15 04:18:19] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2016-07-15 04:18:19] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1545)
[2016-07-15 04:18:19] 	at com.vencillio.rs2.entity.World.process(World.java:322)
[2016-07-15 04:18:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 04:18:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 04:18:19] java.lang.NullPointerException
[2016-07-15 11:38:10] java.lang.NullPointerException
[2016-07-15 11:38:10] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-15 11:38:10] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-15 11:38:10] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-15 11:38:10] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-15 11:38:10] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-15 11:38:10] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 11:38:10] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 13:40:45] java.lang.NullPointerException
[2016-07-15 13:40:45] java.lang.NullPointerException
[2016-07-15 15:03:39] java.lang.NullPointerException
[2016-07-15 15:03:39] java.lang.NullPointerException
[2016-07-15 18:02:01] java.lang.NullPointerException
[2016-07-15 18:02:06] java.lang.NullPointerException
[2016-07-15 18:02:09] java.lang.NullPointerException
[2016-07-15 18:02:15] java.lang.NullPointerException
[2016-07-15 18:02:16] java.lang.NullPointerException
[2016-07-15 18:02:45] java.lang.NullPointerException
[2016-07-15 18:02:47] java.lang.NullPointerException
[2016-07-15 18:02:50] java.lang.NullPointerException
[2016-07-15 18:02:50] java.lang.NullPointerException
[2016-07-15 18:02:50] java.lang.NullPointerException
[2016-07-15 18:02:51] java.lang.NullPointerException
[2016-07-15 18:02:52] java.lang.NullPointerException
[2016-07-15 18:02:53] java.lang.NullPointerException
[2016-07-15 18:02:59] java.lang.NullPointerException
[2016-07-15 18:32:23] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:23] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 18:32:23] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 18:32:23] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 18:32:23] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 18:32:23] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 18:32:23] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 18:32:23] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 18:32:23] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 18:32:23] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 18:32:23] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 18:32:23] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:23] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 18:32:23] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 18:32:23] 	... 9 more
[2016-07-15 18:32:23] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:23] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 18:32:23] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 18:32:23] 	... 10 more
[2016-07-15 18:32:23] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:23] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 18:32:23] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 18:32:23] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 18:32:23] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 18:32:23] 	... 11 more
[2016-07-15 18:32:32] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:32] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 18:32:32] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 18:32:32] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 18:32:32] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 18:32:32] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 18:32:32] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 18:32:32] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 18:32:32] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 18:32:32] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 18:32:32] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 18:32:32] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:32] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 18:32:32] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 18:32:32] 	... 9 more
[2016-07-15 18:32:32] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:32] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 18:32:32] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 18:32:32] 	... 10 more
[2016-07-15 18:32:32] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:32:32] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 18:32:32] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 18:32:32] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 18:32:32] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 18:32:32] 	... 11 more
[2016-07-15 18:33:04] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:33:04] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 18:33:04] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 18:33:04] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 18:33:04] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 18:33:04] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 18:33:04] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 18:33:04] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 18:33:04] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 18:33:04] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 18:33:04] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 18:33:04] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:33:04] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 18:33:04] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 18:33:04] 	... 9 more
[2016-07-15 18:33:04] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:33:04] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 18:33:04] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 18:33:04] 	... 10 more
[2016-07-15 18:33:04] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:33:04] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 18:33:05] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 18:33:05] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 18:33:05] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 18:33:05] 	... 11 more
[2016-07-15 18:47:00] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:47:00] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 18:47:00] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 18:47:00] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 18:47:00] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 18:47:00] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 18:47:00] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 18:47:00] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 18:47:00] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 18:47:00] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 18:47:00] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 18:47:00] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:47:00] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 18:47:00] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 18:47:00] 	... 9 more
[2016-07-15 18:47:00] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:47:00] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 18:47:00] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 18:47:00] 	... 10 more
[2016-07-15 18:47:00] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 18:47:00] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 18:47:00] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 18:47:00] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 18:47:00] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 18:47:00] 	... 11 more
[2016-07-15 19:43:14] com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketTimeoutException: Read timed out
[2016-07-15 19:43:14] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 19:43:14] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 19:43:14] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 19:43:14] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 19:43:14] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 19:43:14] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 19:43:14] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 19:43:14] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 19:43:14] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 19:43:14] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 19:43:14] Caused by: java.net.SocketTimeoutException: Read timed out
[2016-07-15 19:43:14] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2016-07-15 19:43:14] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2016-07-15 19:43:14] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-15 19:43:14] 	at java.net.SocketInputStream.read(Unknown Source)
[2016-07-15 19:43:14] 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
[2016-07-15 19:43:14] 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
[2016-07-15 19:43:14] 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
[2016-07-15 19:43:14] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
[2016-07-15 19:43:14] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[2016-07-15 19:43:14] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
[2016-07-15 19:43:14] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
[2016-07-15 19:43:14] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
[2016-07-15 19:43:14] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
[2016-07-15 19:43:14] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
[2016-07-15 19:43:14] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
[2016-07-15 19:43:14] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
[2016-07-15 19:43:14] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
[2016-07-15 19:43:14] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
[2016-07-15 19:43:14] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[2016-07-15 19:43:14] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[2016-07-15 19:43:14] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
[2016-07-15 19:43:14] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
[2016-07-15 19:43:14] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
[2016-07-15 19:43:14] 	... 9 more
[2016-07-15 19:44:25] com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 19:44:25] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
[2016-07-15 19:44:25] 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
[2016-07-15 19:44:25] 	at com.motivoters.motivote.MotivoteService.callAPI(MotivoteService.java:37)
[2016-07-15 19:44:25] 	at com.motivoters.motivote.MotivoteService.redeemVote(MotivoteService.java:96)
[2016-07-15 19:44:25] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.lambda$0(PlayerCommand.java:64)
[2016-07-15 19:44:25] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2016-07-15 19:44:25] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2016-07-15 19:44:25] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2016-07-15 19:44:25] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2016-07-15 19:44:25] 	at java.lang.Thread.run(Unknown Source)
[2016-07-15 19:44:25] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 19:44:25] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
[2016-07-15 19:44:25] 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
[2016-07-15 19:44:25] 	... 9 more
[2016-07-15 19:44:25] Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 19:44:25] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
[2016-07-15 19:44:25] 	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
[2016-07-15 19:44:25] 	... 10 more
[2016-07-15 19:44:25] Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
[2016-07-15 19:44:25] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[2016-07-15 19:44:25] 	at org.json.JSONArray.<init>(JSONArray.java:105)
[2016-07-15 19:44:25] 	at org.json.JSONArray.<init>(JSONArray.java:144)
[2016-07-15 19:44:25] 	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
[2016-07-15 19:44:25] 	... 11 more
[2016-07-15 19:46:36] java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 12
[2016-07-15 19:46:36] 	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
[2016-07-15 19:46:36] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:120)
[2016-07-15 19:46:36] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:107)
[2016-07-15 19:46:36] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:467)
[2016-07-15 19:46:36] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:412)
[2016-07-15 19:46:36] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:768)
[2016-07-15 19:46:36] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-15 19:46:36] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-15 19:46:36] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-15 19:46:36] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-15 19:46:36] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-15 20:00:43] java.lang.ArrayIndexOutOfBoundsException
[2016-07-16 00:32:16] java.lang.NullPointerException
[2016-07-16 00:32:16] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:32:16] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:32:16] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:32:16] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:32:16] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:32:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:32:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:38:52] java.lang.NullPointerException
[2016-07-16 00:38:52] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:38:52] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:38:52] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:38:52] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:38:52] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:38:52] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:38:52] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:39:34] java.lang.NullPointerException
[2016-07-16 00:39:34] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:39:34] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:39:34] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:39:34] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:39:34] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:39:34] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:39:34] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:40:10] java.lang.NullPointerException
[2016-07-16 00:40:10] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:40:10] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:40:10] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:40:10] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:40:10] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:40:10] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:40:10] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:40:19] java.lang.NullPointerException
[2016-07-16 00:40:19] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:40:19] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:40:19] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:40:19] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:40:19] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:40:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:40:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:40:29] java.lang.NullPointerException
[2016-07-16 00:40:29] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:40:29] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:40:29] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:40:29] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:40:29] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:40:29] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:40:29] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:40:50] java.lang.NullPointerException
[2016-07-16 00:40:50] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:40:50] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:40:50] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:40:50] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:40:50] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:40:50] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:40:50] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:40:52] java.lang.NullPointerException
[2016-07-16 00:40:52] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:40:52] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:40:52] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:40:52] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:40:52] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:40:52] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:40:52] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:40:53] java.lang.NullPointerException
[2016-07-16 00:40:53] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:40:53] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:40:53] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:40:53] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:40:53] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:40:53] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:40:53] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:44:47] java.lang.NullPointerException
[2016-07-16 00:44:47] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:44:47] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:44:47] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:44:47] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:44:47] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:44:47] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:44:47] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 00:44:51] java.lang.NullPointerException
[2016-07-16 00:44:51] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 00:44:51] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 00:44:51] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 00:44:51] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 00:44:51] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 00:44:51] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 00:44:51] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 03:05:51] java.lang.NullPointerException
[2016-07-16 03:05:51] java.lang.NullPointerException
[2016-07-16 03:34:25] java.lang.NullPointerException
[2016-07-16 03:34:25] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2016-07-16 03:34:25] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:118)
[2016-07-16 03:34:25] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 03:34:25] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 03:34:25] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 03:34:25] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 03:34:25] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 04:18:56] java.lang.NullPointerException
[2016-07-16 04:18:56] 	at com.vencillio.rs2.content.GenieReset.handle(GenieReset.java:118)
[2016-07-16 04:18:56] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:923)
[2016-07-16 04:18:56] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 04:18:56] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 04:18:56] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 04:18:56] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 04:18:56] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 06:18:25] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 06:18:25] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 06:18:25] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 06:18:25] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 06:18:25] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 06:18:25] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 06:18:25] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 06:18:25] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 06:18:29] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 06:18:29] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 06:18:29] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 06:18:29] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 06:18:29] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 06:18:29] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 06:18:29] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 06:18:29] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 06:18:40] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 06:18:40] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 06:18:40] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 06:18:40] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 06:18:40] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 06:18:40] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 06:18:40] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 06:18:40] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 06:18:43] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 06:18:43] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 06:18:43] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 06:18:43] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 06:18:43] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 06:18:43] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 06:18:43] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 06:18:43] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 06:27:16] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 06:27:16] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 06:27:16] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 06:27:16] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 06:27:16] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 06:27:16] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 06:27:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 06:27:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 06:27:22] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 06:27:22] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 06:27:22] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 06:27:22] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 06:27:22] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 06:27:22] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 06:27:22] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 06:27:22] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 07:35:51] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 07:35:51] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 07:35:51] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 07:35:51] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 07:35:51] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 07:35:51] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 07:35:51] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 07:35:51] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 07:35:58] java.lang.ArrayIndexOutOfBoundsException: 998
[2016-07-16 07:35:58] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:335)
[2016-07-16 07:35:58] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2016-07-16 07:35:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2016-07-16 07:35:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2016-07-16 07:35:58] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2016-07-16 07:35:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2016-07-16 07:35:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2016-07-16 16:18:01] java.lang.NullPointerException
[2016-07-16 16:18:01] java.lang.NullPointerException
[2016-07-16 18:12:15] java.lang.NullPointerException
[2016-07-16 18:12:15] 	at com.vencillio.rs2.content.skill.mining.Mining$Pickaxe.get(Mining.java:118)
[2016-07-16 18:12:15] 	at com.vencillio.rs2.content.skill.mining.Mining.clickRock(Mining.java:223)
[2016-07-16 18:12:15] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1044)
[2016-07-16 18:12:15] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:308)
[2016-07-16 18:12:15] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2016-07-16 18:12:15] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2016-07-16 18:12:15] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2016-07-16 18:12:15] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2016-07-16 18:12:15] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
