Logging started at 2017-01-31 03:02:35
File name: C:\Users\Administrator\Desktop\new new source\.\data\logs\err\1485860555498 - Administrator - [Tue Jan 31][3.02AM].txt
System.getProperty("os.name"): "Windows Server 2012 R2"

[2017-01-31 18:39:02] java.lang.NullPointerException
[2017-01-31 18:39:02] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1608)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.entity.World.process(World.java:322)
[2017-01-31 18:39:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-01-31 18:39:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-01-31 18:39:02] java.lang.NullPointerException
[2017-01-31 18:39:02] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:388)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1534)
[2017-01-31 18:39:02] 	at com.vencillio.rs2.entity.World.process(World.java:335)
[2017-01-31 18:39:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-01-31 18:39:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-01-31 21:06:06] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-01-31 21:06:06] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-01-31 21:06:06] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:121)
[2017-01-31 21:06:06] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-01-31 21:06:06] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-01-31 21:06:06] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-01-31 21:06:06] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2017-01-31 21:06:06] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2017-01-31 21:06:06] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2017-01-31 21:06:06] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-02-01 01:46:53] java.lang.ArrayIndexOutOfBoundsException: 0
[2017-02-01 01:46:53] 	at com.vencillio.core.util.Utility.randomElement(Utility.java:638)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.content.CrystalChest.searchChest(CrystalChest.java:97)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.WalkToActions.finishObjectClick(WalkToActions.java:1860)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.WalkToActions$7.onDestination(WalkToActions.java:311)
[2017-02-01 01:46:53] 	at com.vencillio.core.task.impl.WalkToTask.execute(WalkToTask.java:39)
[2017-02-01 01:46:53] 	at com.vencillio.core.task.TaskQueue.queue(TaskQueue.java:117)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.WalkToActions.clickObject(WalkToActions.java:306)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.player.net.in.impl.ObjectPacket.handle(ObjectPacket.java:71)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-02-01 01:46:53] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-02-01 01:46:53] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-02-01 01:46:53] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-02-01 02:20:02] java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 12
[2017-02-01 02:20:02] 	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
[2017-02-01 02:20:02] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:120)
[2017-02-01 02:20:02] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:107)
[2017-02-01 02:20:02] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:467)
[2017-02-01 02:20:02] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:412)
[2017-02-01 02:20:02] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:768)
[2017-02-01 02:20:02] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-02-01 02:20:02] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-02-01 02:20:02] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-02-01 02:20:02] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-02-01 02:20:02] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-02-01 02:37:18] java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 12
[2017-02-01 02:37:18] 	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
[2017-02-01 02:37:18] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:120)
[2017-02-01 02:37:18] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:107)
[2017-02-01 02:37:18] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:467)
[2017-02-01 02:37:18] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:412)
[2017-02-01 02:37:18] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:768)
[2017-02-01 02:37:18] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-02-01 02:37:18] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-02-01 02:37:18] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-02-01 02:37:18] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-02-01 02:37:18] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-02-01 05:26:16] java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 12
[2017-02-01 05:26:16] 	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
[2017-02-01 05:26:16] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:120)
[2017-02-01 05:26:16] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:107)
[2017-02-01 05:26:16] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:467)
[2017-02-01 05:26:16] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:412)
[2017-02-01 05:26:16] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:768)
[2017-02-01 05:26:16] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2017-02-01 05:26:16] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:270)
[2017-02-01 05:26:16] 	at com.vencillio.rs2.entity.World.process(World.java:320)
[2017-02-01 05:26:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2017-02-01 05:26:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2017-02-01 05:40:56] com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 88 column 14
[2017-02-01 05:40:56] 	at com.google.gson.Gson.fromJson(Gson.java:809)
[2017-02-01 05:40:56] 	at com.google.gson.Gson.fromJson(Gson.java:734)
[2017-02-01 05:40:56] 	at com.vencillio.rs2.content.io.PlayerSave$PlayerDetails.loadDetails(PlayerSave.java:420)
[2017-02-01 05:40:56] 	at com.vencillio.rs2.content.io.PlayerSave.load(PlayerSave.java:1103)
[2017-02-01 05:40:56] 	at com.vencillio.core.LoginThread.cycle(LoginThread.java:26)
[2017-02-01 05:40:56] 	at com.vencillio.core.LoginThread.run(LoginThread.java:83)
[2017-02-01 05:40:56] Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 88 column 14
[2017-02-01 05:40:56] 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1310)
[2017-02-01 05:40:56] 	at com.google.gson.stream.JsonReader.nextInArray(JsonReader.java:673)
[2017-02-01 05:40:56] 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:376)
[2017-02-01 05:40:56] 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:349)
[2017-02-01 05:40:56] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:71)
[2017-02-01 05:40:56] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
[2017-02-01 05:40:56] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
[2017-02-01 05:40:56] 	at com.google.gson.Gson.fromJson(Gson.java:795)
[2017-02-01 05:40:56] 	... 5 more
